---
- name: Fetch minikube
  get_url: 
    url: "{{ minikube_download_url }}{{ minikube_version }}/minikube-linux-amd64"
    checksum: "{{ minikube_checksum }}"
    dest: /usr/local/bin/minikube
    mode: 0755
    owner: root
    group: root
  become: true

- name: Write minikube profile
  copy:
    src: minikube.sh
    dest: /etc/profile.d/minikube.sh
    mode: 0644
    owner: root
    group: root
