---
- src: https://github.com/UKHomeOffice/ansible-base-role.git
  version: 7b586e7c7d29ee3c1918e219a0b1e36edef23268
  name: generic
- src: https://github.com/UKHomeOffice/ansible-gui-role.git
  version: edcded91ec07e2f843df0c539a149175c4fa0f98
  name: gui
